"""initial schema

Revision ID: d5bd7c49e784
Revises: 
Create Date: 2026-07-08 20:56:50.656440

"""
from alembic import op
import sqlalchemy as sa


revision = 'd5bd7c49e784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('rate_paise', sa.Integer(), nullable=False),
    sa.Column('common_area_units', sa.Integer(), nullable=False),
    sa.Column('ev_units', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month')
    )
    op.create_table('charge_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('default_amount_paise', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('meter_no', sa.String(length=40), nullable=False),
    sa.Column('common_share_bps', sa.Integer(), nullable=False),
    sa.Column('has_ev', sa.Boolean(), nullable=False),
    sa.Column('opening_reading', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='billstatus'), nullable=False),
    sa.Column('prev_reading', sa.Integer(), nullable=False),
    sa.Column('curr_reading', sa.Integer(), nullable=False),
    sa.Column('own_units', sa.Integer(), nullable=False),
    sa.Column('common_share_units', sa.Integer(), nullable=False),
    sa.Column('ev_units', sa.Integer(), nullable=False),
    sa.Column('billable_units', sa.Integer(), nullable=False),
    sa.Column('rate_paise', sa.Integer(), nullable=False),
    sa.Column('electricity_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['billing_periods.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'period_id')
    )
    op.create_table('unit_charge_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('default_amount_paise', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superuser', 'admin', 'tenant', name='role'), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('uq_active_tenant_per_unit', 'users', ['unit_id'], unique=True, sqlite_where=sa.text("role = 'tenant' AND is_active = 1 AND unit_id IS NOT NULL"), postgresql_where=sa.text("role = 'tenant' AND is_active AND unit_id IS NOT NULL"))
    op.create_table('admin_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'unit_id')
    )
    op.create_table('charge_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('reading', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['billing_periods.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'period_id')
    )
    op.create_table('reading_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['meter_readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_photos')
    op.drop_table('meter_readings')
    op.drop_table('charge_lines')
    op.drop_table('admin_scopes')
    op.drop_index('uq_active_tenant_per_unit', table_name='users', sqlite_where=sa.text("role = 'tenant' AND is_active = 1 AND unit_id IS NOT NULL"), postgresql_where=sa.text("role = 'tenant' AND is_active AND unit_id IS NOT NULL"))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('unit_charge_defaults')
    op.drop_table('bills')
    op.drop_table('units')
    op.drop_table('charge_templates')
    op.drop_table('billing_periods')
    # ### end Alembic commands ###
